Repository 67P/hyperchannel, pull requests merged in 2019-06, with the labels that each got.

#167 Partial message rendering
  app/components/channel-container/component.js
  app/components/channel-container/template.hbs
  app/components/scrolling-observer/component.js
Labels: kredits-3

#172 Don't send emails for successful Travis builds
  .travis.yml
Labels: kredits-1

#171 Refactor actions to remove ember-route-action-helper dependency
  app/components/channel-container/component.js
  app/components/channel-nav/component.js
  app/components/channel-nav/template.hbs
  app/controllers/space/base_channel.js
  app/routes/application.js
  app/templates/application.hbs
  app/templates/space/channel.hbs
  package-lock.json
  package.json
Labels: kredits-2

#169 Disconnect IntersectionObserver when destroying component
  app/components/scrolling-observer/component.js
Labels: kredits-1

#168 Show own messages in different windows.
  app/controllers/space/base_channel.js
  app/services/sockethub-irc.js
  app/utils/channel-message-from-sockethub-object.js
Labels: kredits-2

#173 Improve production builds and deployment
  package.json
  scripts/deploy.sh
  scripts/update-version-file.sh
Labels: kredits-1, ops
