Repository 67P/hyperchannel, pull requests merged in 2021-12, with the labels that each got.

#255 Integration tests for join-channel-* components
  app/components/join-channel-xmpp/template.hbs
  tests/integration/components/join-channel-irc/component-test.js
  tests/integration/components/join-channel-xmpp/component-test.js
Labels: kredits-1

#254 UI for joining channels
  app/components/account-list/template.hbs
  app/components/add-chat-account-irc/template.hbs
  app/components/add-chat-account-xmpp/template.hbs
  app/components/channel-nav/component.js
  app/components/join-channel-irc/component.js
  app/components/join-channel-irc/template.hbs
  app/components/join-channel-xmpp/component.js
  app/components/join-channel-xmpp/template.hbs
  app/components/join-channel/component.js
  app/components/join-channel/template.hbs
  app/components/message-input/component.js
  app/components/message-input/template.hbs
  package-lock.json
  package.json
  tests/integration/components/add-chat-account-irc/component-test.js
  tests/integration/components/add-chat-account-xmpp/component-test.js
  tests/integration/components/join-channel-irc/component-test.js
  tests/integration/components/join-channel-xmpp/component-test.js
  tests/integration/components/join-channel/component-test.js
Labels: kredits-2

#258 Update Ember to 3.24.6
  .codeclimate.yml
  .eslintignore
  .eslintrc.js
  .gitignore
  .template-lintrc.js
  app/templates/application.hbs
  config/ember-cli-update.json
  config/environment.js
  config/targets.js
  ember-cli-build.js
  package-lock.json
  package.json
  testem.js
  tests/index.html
  tests/test-helper.js
Labels: kredits-2

#259 Adapt to new AS2.0 names
  app/components/add-chat-account-irc/component.js
  app/components/add-chat-account-xmpp/component.js
  app/services/coms.js
  app/services/sockethub-irc.js
  app/services/sockethub-xmpp.js
  app/utils/channel-message-from-sockethub-object.js
  package-lock.json
  tests/unit/services/coms-test.js
  tests/unit/services/sockethub-xmpp-test.js
  tests/unit/utils/channel-message-from-sockethub-object-test.js
Labels: kredits-2

#260 Remove "extend" module in favor of modern JS
  app/services/sockethub-irc.js
  app/services/sockethub-xmpp.js
  package-lock.json
  package.json
Labels: kredits-1

#262 Port date headline/divider CSS to Tailwind
  app/components/date-headline/template.hbs
  app/styles/app.scss
  app/styles/components/date-headline.scss
Labels: kredits-1

#261 Add incoming message corrections
  app/components/message-chat/template.hbs
  app/models/base_channel.js
  app/models/message.js
  app/templates/components/icon-edit.hbs
  app/utils/channel-message-from-sockethub-object.js
  tests/unit/models/base-channel-test.js
Labels: xmpp, kredits-2
