Repository 67P/hyperchannel, pull requests merged in 2021-04, with the labels that each got.

#210 Update Ember to latest LTS version
  .eslintrc.js
  .travis.yml
  app/app.js
  app/components/app-container/component.js
  app/components/app-container/template.hbs
  app/controllers/application.js
  app/router.js
  app/templates/application.hbs
  config/ember-cli-update.json
  config/targets.js
  jsconfig.json
  package-lock.json
  package.json
  tests/integration/components/app-container-test.js
  tests/test-helper.js
Labels: kredits-2

#213 Fix mobile sidebar issue
  app/components/channel-container/template.hbs
  app/controllers/application.js
  app/controllers/space/base_channel.js
  app/routes/space/channel.js
  app/routes/space/channel/shares.js
Labels: kredits-1

#216 Fix date-headline markup
  app/components/date-headline/template.hbs
Labels: kredits-1

#215 Add missing arguments to ChannelContainer for DM channel
  app/templates/space/user_channel.hbs
Labels: kredits-1

#217 Update dependencies, Ember things
  .codeclimate.yml
  .eslintrc.js
  .template-lintrc.js
  app/components/channel-container/template.hbs
  app/components/icon-at-sign.js
  app/components/icon-info.js
  app/components/icon-log-out.js
  app/components/icon-paperclip.js
  app/components/icon-settings.js
  app/components/icon-users.js
  app/components/notification-topic-change/component.js
  app/components/space-setting-modal/template.hbs
  app/components/user-list/template.hbs
  app/components/web-push-subscription/template.hbs
  app/services/coms.js
  app/templates/settings.hbs
  app/templates/space/channel.hbs
  app/templates/space/user_channel.hbs
  config/targets.js
  package-lock.json
  package.json
  scripts/fix-git-urls.js
  tests/index.html
  tests/test-helper.js
  tests/unit/services/coms-test.js
Labels: kredits-2

#218 Set up Tailwind CSS with PurgeCSS and JIT compilation
  .browserslistrc
  .codeclimate.yml
  app/components/message-input/template.hbs
  app/styles/_layout.scss
  app/styles/app.scss
  app/styles/components/message-input.scss
  config/tailwindcss-config.js
  ember-cli-build.js
  package-lock.json
  package.json
Labels: dev environment, kredits-2

#220 Fix user settings in localStorage
  app/routes/application.js
  app/routes/index.js
  app/routes/space/base_channel.js
  app/services/coms.js
  app/services/local-data.js
  app/storages/user-settings.js
  package-lock.json
  package.json
  tests/unit/services/local-data-test.js
Labels: bug, feature, kredits-2
